/**
 * @file hal_stm32.c
 * @brief STM32 HAL implementation for Rule Engine
 *
 * Maps Rule Engine HAL calls to STM32 HAL/LL drivers.
 * Include this file only when building for STM32_PLATFORM.
 *
 * Customise the peripheral mappings in config.h (generated by Python tool).
 */

#ifdef STM32_PLATFORM

#include "re_hal.h"
#include "re_logger.h"
#include "config.h"          /* Generated: sensor/output pin maps */

/* STM32 HAL headers — adjust for your MCU family */
#include "stm32g4xx_hal.h"

/* =========================================================================
 * External handles (defined in main.c or peripheral init files)
 * ========================================================================= */
extern ADC_HandleTypeDef  hadc1;
extern I2C_HandleTypeDef  hi2c1;
extern UART_HandleTypeDef huart2;
extern RTC_HandleTypeDef  hrtc;

/* =========================================================================
 * Log ring buffer (Flash-backed via HAL_FLASH_Program on STM32)
 * Define RE_LOG_FLASH_ADDR in config.h to enable flash logging.
 * ========================================================================= */
#define STM32_RAM_LOG_SIZE (128U)
static RE_LogEntry_t s_ram_log[STM32_RAM_LOG_SIZE];
static uint16_t      s_ram_log_head  = 0U;
static uint16_t      s_ram_log_count = 0U;

/* =========================================================================
 * HAL_RE_Init
 * ========================================================================= */
RE_Status_t HAL_RE_Init(void)
{
    /* GPIOs and peripherals are configured by CubeMX-generated code.
     * Here we only do application-level init. */
    RE_LOG_INFO("STM32 Rule Engine HAL initialised");
    return RE_OK;
}

void HAL_RE_DeInit(void)
{
    /* Drive all outputs to failsafe via config table if needed */
}

/* =========================================================================
 * HAL_ReadSensor
 *
 * Sensor-to-peripheral mapping comes from config.h generated by Python tool.
 * Example generated snippet:
 *
 *   #define SENSOR_1_ADC_CHANNEL  ADC_CHANNEL_1
 *   #define SENSOR_1_GPIO_PORT    NULL
 *
 * For I2C sensors (e.g. temperature, humidity) the HAL dispatches to the
 * appropriate driver. Add actual sensor driver calls below.
 * ========================================================================= */
RE_Status_t HAL_ReadSensor(uint8_t sensor_id, SensorValue_t *value)
{
    HAL_StatusTypeDef hal_ret;
    uint32_t          adc_raw;
    uint32_t          gpio_val;

    if ((sensor_id == 0U) || (value == NULL))
    {
        return RE_ERR_INVALID_ID;
    }

    /* Dispatch based on generated config table */
    switch (RE_SensorGetInterface(sensor_id))
    {
        case RE_SENSOR_IF_ADC:
        {
            ADC_ChannelConfTypeDef cfg = {0};
            cfg.Channel      = RE_SensorGetADCChannel(sensor_id);
            cfg.Rank         = ADC_REGULAR_RANK_1;
            cfg.SamplingTime = ADC_SAMPLETIME_47CYCLES_5;
            cfg.SingleDiff   = ADC_SINGLE_ENDED;
            cfg.OffsetNumber = ADC_OFFSET_NONE;

            if (HAL_ADC_ConfigChannel(&hadc1, &cfg) != HAL_OK)
            {
                return RE_ERR_HAL;
            }
            if (HAL_ADC_Start(&hadc1) != HAL_OK)
            {
                return RE_ERR_HAL;
            }
            hal_ret = HAL_ADC_PollForConversion(&hadc1, 10U);
            if (hal_ret != HAL_OK)
            {
                HAL_ADC_Stop(&hadc1);
                return RE_ERR_HAL;
            }
            adc_raw = HAL_ADC_GetValue(&hadc1);
            HAL_ADC_Stop(&hadc1);

            /* Scale: 12-bit ADC → engineering unit (x100)
             * Example: 0..4095 → 0..330000 (0..3300 mV scaled x100)
             * Actual formula depends on sensor type — fill from config */
            *value = (SensorValue_t)((adc_raw * RE_SensorGetScale(sensor_id)) / 4095U);
            break;
        }

        case RE_SENSOR_IF_GPIO:
        {
            GPIO_TypeDef *port = RE_SensorGetGPIOPort(sensor_id);
            uint16_t      pin  = RE_SensorGetGPIOPin(sensor_id);
            gpio_val           = HAL_GPIO_ReadPin(port, pin);
            *value             = (SensorValue_t)(gpio_val != GPIO_PIN_RESET ? 100 : 0);
            break;
        }

        case RE_SENSOR_IF_I2C:
        {
            /* Placeholder: call your sensor-specific I2C driver here */
            /* e.g., SHT30_ReadTemperature(&hi2c1, value); */
            *value = 0;
            break;
        }

        default:
            return RE_ERR_INVALID_PARAM;
    }

    return RE_OK;
}

/* =========================================================================
 * HAL_WriteOutput
 * ========================================================================= */
RE_Status_t HAL_WriteOutput(uint8_t output_id, uint8_t state)
{
    GPIO_TypeDef *port;
    uint16_t      pin;
    GPIO_PinState gpio_state;

    if ((output_id == 0U) || (output_id > RE_MAX_OUTPUTS))
    {
        return RE_ERR_INVALID_ID;
    }

    port       = RE_OutputGetGPIOPort(output_id);  /* Generated lookup */
    pin        = RE_OutputGetGPIOPin(output_id);
    gpio_state = (state != 0U) ? GPIO_PIN_SET : GPIO_PIN_RESET;

    HAL_GPIO_WritePin(port, pin, gpio_state);

    return RE_OK;
}

/* =========================================================================
 * HAL_GetRTC
 * ========================================================================= */
RE_Status_t HAL_GetRTC(RE_RTC_t *rtc)
{
    RTC_TimeTypeDef sTime = {0};
    RTC_DateTypeDef sDate = {0};

    if (rtc == NULL)
    {
        return RE_ERR_NULL_PTR;
    }

    if (HAL_RTC_GetTime(&hrtc, &sTime, RTC_FORMAT_BIN) != HAL_OK)
    {
        return RE_ERR_HAL;
    }
    if (HAL_RTC_GetDate(&hrtc, &sDate, RTC_FORMAT_BIN) != HAL_OK)
    {
        return RE_ERR_HAL;
    }

    rtc->hour    = sTime.Hours;
    rtc->minute  = sTime.Minutes;
    rtc->second  = sTime.Seconds;
    rtc->day     = sDate.Date;
    rtc->month   = sDate.Month;
    rtc->year    = (uint16_t)(2000U + sDate.Year);
    rtc->weekday = (uint8_t)(sDate.WeekDay % 7U);  /* STM32: Mon=1..Sun=7, map to Sun=0 */

    return RE_OK;
}

/* =========================================================================
 * HAL_GetTimestamp — seconds since epoch via RTC
 * ========================================================================= */
RE_Timestamp_t HAL_GetTimestamp(void)
{
    RE_RTC_t rtc;
    if (HAL_GetRTC(&rtc) != RE_OK)
    {
        return (RE_Timestamp_t)HAL_GetTick() / 1000U;
    }
    /* Simple seconds-of-day counter; replace with full mktime if needed */
    return (RE_Timestamp_t)(rtc.hour * 3600U + rtc.minute * 60U + rtc.second);
}

/* =========================================================================
 * HAL_GetMicros — using DWT cycle counter (ARM Cortex-M)
 * ========================================================================= */
uint32_t HAL_GetMicros(void)
{
    return (uint32_t)(DWT->CYCCNT / (SystemCoreClock / 1000000U));
}

/* =========================================================================
 * HAL_LogEvent — RAM ring buffer + optional Flash
 * ========================================================================= */
RE_Status_t HAL_LogEvent(const RE_LogEntry_t *entry)
{
    if (entry == NULL)
    {
        return RE_ERR_NULL_PTR;
    }

    HAL_EnterCritical();
    s_ram_log[s_ram_log_head] = *entry;
    s_ram_log_head            = (uint16_t)((s_ram_log_head + 1U) % STM32_RAM_LOG_SIZE);
    if (s_ram_log_count < STM32_RAM_LOG_SIZE)
    {
        s_ram_log_count++;
    }
    HAL_ExitCritical();

    /* Optional: also write to Flash sector — implement Flash write here */

    return RE_OK;
}

RE_Status_t HAL_ReadLog(RE_LogEntry_t *buf, uint16_t count, uint16_t *read)
{
    uint16_t i;
    uint16_t to_read;
    uint16_t start;

    if ((buf == NULL) || (read == NULL))
    {
        return RE_ERR_NULL_PTR;
    }

    to_read = (count < s_ram_log_count) ? count : s_ram_log_count;
    *read   = to_read;
    start   = (s_ram_log_head >= to_read)
                  ? (uint16_t)(s_ram_log_head - to_read)
                  : (uint16_t)(STM32_RAM_LOG_SIZE - (to_read - s_ram_log_head));

    for (i = 0U; i < to_read; i++)
    {
        buf[i] = s_ram_log[(start + i) % STM32_RAM_LOG_SIZE];
    }

    return RE_OK;
}

void HAL_ClearLog(void)
{
    HAL_EnterCritical();
    s_ram_log_head  = 0U;
    s_ram_log_count = 0U;
    HAL_ExitCritical();
}

/* =========================================================================
 * Watchdog
 * ========================================================================= */
extern IWDG_HandleTypeDef hiwdg;

void HAL_KickWatchdog(void)
{
    (void)HAL_IWDG_Refresh(&hiwdg);
}

/* =========================================================================
 * Critical Section (disables IRQs on Cortex-M)
 * ========================================================================= */
void HAL_EnterCritical(void)
{
    __disable_irq();
}

void HAL_ExitCritical(void)
{
    __enable_irq();
}

/* =========================================================================
 * RE_UART_Printf — used by RE_LOG macros
 * ========================================================================= */
void RE_UART_Printf(const char *fmt, ...)
{
    char    buf[128];
    va_list args;
    int     len;

    va_start(args, fmt);
    len = vsnprintf(buf, sizeof(buf), fmt, args);
    va_end(args);

    if (len > 0)
    {
        (void)HAL_UART_Transmit(&huart2, (uint8_t *)buf, (uint16_t)len, 100U);
    }
}

#endif /* STM32_PLATFORM */
