/**
 * @file main_stm32.c
 * @brief STM32 Rule Engine application entry point
 *
 * Place this file in platform/stm32/Src/
 * Generated by CubeMX peripheral init is in same directory.
 *
 * FreeRTOS task-based execution: one task for rule engine,
 * one for UART diagnostics.
 */

#ifdef STM32_PLATFORM

#include "main.h"
#include "re_engine.h"
#include "re_hal.h"
#include "re_logger.h"
#include "config.h"

/* FreeRTOS */
#include "FreeRTOS.h"
#include "task.h"

/* =========================================================================
 * Task configuration
 * ========================================================================= */
#define RULE_ENGINE_TASK_STACK  (512U)   /* words */
#define RULE_ENGINE_TASK_PRIO   (tskIDLE_PRIORITY + 2U)
#define DIAG_TASK_STACK         (256U)
#define DIAG_TASK_PRIO          (tskIDLE_PRIORITY + 1U)

/* Rule engine execution period */
#define RE_TICK_PERIOD_MS       (100U)

/* =========================================================================
 * Task implementations
 * ========================================================================= */
static void RuleEngineTask(void *arg)
{
    TickType_t  xLastWakeTime;
    RE_Status_t ret;

    (void)arg;

    ret = RE_Init();
    if (ret != RE_OK)
    {
        RE_LOG_ERROR("RE_Init failed: %d", (int)ret);
        vTaskDelete(NULL);
        return;
    }

    xLastWakeTime = xTaskGetTickCount();

    for (;;)
    {
        (void)RE_Tick();

        /* Periodic wakeup — deterministic loop period */
        vTaskDelayUntil(&xLastWakeTime, pdMS_TO_TICKS(RE_TICK_PERIOD_MS));
    }
}

static void DiagnosticsTask(void *arg)
{
    (void)arg;

    for (;;)
    {
        vTaskDelay(pdMS_TO_TICKS(10000U));  /* Print every 10 seconds */
        RE_PrintDiagnostics();
    }
}

/* =========================================================================
 * Application entry (called from CubeMX-generated main after HAL_Init)
 * ========================================================================= */
void App_Main(void)
{
    BaseType_t xRet;

    /* Enable DWT cycle counter for HAL_GetMicros */
    CoreDebug->DEMCR |= CoreDebug_DEMCR_TRCENA_Msk;
    DWT->CYCCNT       = 0U;
    DWT->CTRL        |= DWT_CTRL_CYCCNTENA_Msk;

    xRet = xTaskCreate(RuleEngineTask,
                       "RuleEngine",
                       RULE_ENGINE_TASK_STACK,
                       NULL,
                       RULE_ENGINE_TASK_PRIO,
                       NULL);
    configASSERT(xRet == pdPASS);

    xRet = xTaskCreate(DiagnosticsTask,
                       "Diagnostics",
                       DIAG_TASK_STACK,
                       NULL,
                       DIAG_TASK_PRIO,
                       NULL);
    configASSERT(xRet == pdPASS);

    vTaskStartScheduler();

    /* Should never reach here */
    for (;;) {}
}

#endif /* STM32_PLATFORM */
