#!/usr/bin/env python3
"""
fw_gen.py — Firmware Code Generator
====================================
Scans all EventConfig*.h files and merges them into a single EventList.h.
Also validates for ID collisions across modules.

Usage:
    python3 tools/fw_gen.py --event-dir src/event/configs --out generated/

EventConfig*.h format expected:
  - One typedef enum { ... } <Name>Events_t;
  - Each entry: EVT_SOME_NAME = 0xNNNN,   (hex preferred)
  - Comment tag:  @BASE_ID: 0xNNNN  (optional, for documentation)
  - Comment tag:  @EVENT_MODULE: ModuleName
"""

import os
import re
import sys
import argparse
from pathlib import Path
from datetime import datetime


# ── Regex patterns ──────────────────────────────────────────────────────────
RE_MODULE_TAG = re.compile(r'@EVENT_MODULE:\s*(\w+)')
RE_BASE_TAG   = re.compile(r'@BASE_ID:\s*(0x[0-9A-Fa-f]+|\d+)')
RE_ENUM_ENTRY = re.compile(
    r'^\s*#define\s+(EVT_\w+)\s+(0x[0-9A-Fa-f]+|\d+)U?',
    re.MULTILINE
)


def parse_event_config(path: Path) -> dict:
    """Extract module name, base ID, and all EVT_* entries from one file."""
    text = path.read_text(encoding='utf-8')

    module_m = RE_MODULE_TAG.search(text)
    base_m   = RE_BASE_TAG.search(text)

    module = module_m.group(1) if module_m else path.stem.replace('EventConfig', '')
    base   = int(base_m.group(1), 0) if base_m else None

    events = {}
    for m in RE_ENUM_ENTRY.finditer(text):
        name  = m.group(1)
        value = int(m.group(2), 0)
        events[name] = value

    return {'module': module, 'base': base, 'events': events, 'file': path.name}


def validate(modules: list) -> list[str]:
    """Check for duplicate event IDs across modules. Return list of error strings."""
    seen = {}  # value → (name, module)
    errors = []
    for m in modules:
        for name, val in m['events'].items():
            if val in seen:
                prev_name, prev_mod = seen[val]
                errors.append(
                    f"ID COLLISION: 0x{val:04X}  "
                    f"{prev_mod}::{prev_name}  vs  {m['module']}::{name}"
                )
            else:
                seen[val] = (name, m['module'])
    return errors


def generate_event_list(modules: list, out_path: Path) -> None:
    """Write generated/EventList.h merging all modules."""
    all_events = []
    for m in modules:
        for name, val in sorted(m['events'].items(), key=lambda x: x[1]):
            all_events.append((name, val, m['module']))

    lines = [
        '/**',
        ' * @file EventList.h',
        ' * @brief AUTO-GENERATED — do not edit by hand.',
        ' *',
        f' * Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}',
        ' * Source:     EventConfig*.h files in src/event/configs/',
        ' *',
        ' * This file is the single source of truth for all event IDs.',
        ' * Include it (directly or via event_bus.h) to use EVT_* constants.',
        ' */',
        '',
        '#ifndef EVENT_LIST_H',
        '#define EVENT_LIST_H',
        '',
        '#include <stdint.h>',
        '',
        '/* Event ID type */',
        'typedef uint16_t EventID_t;',
        '',
        '/* Sentinel */',
        '#define EVT_INVALID  0x0000U',
        '',
    ]

    current_module = None
    for name, val, mod in sorted(all_events, key=lambda x: x[1]):
        if mod != current_module:
            if current_module is not None:
                lines.append('')
            lines.append(f'/* ── {mod} events ── */')
            current_module = mod
        lines.append(f'#define {name:<40s} 0x{val:04X}U')

    lines += [
        '',
        f'#define EVT__COUNT  {len(all_events)}U  /* total registered events */',
        '',
        '#endif /* EVENT_LIST_H */',
        '',
    ]

    out_path.write_text('\n'.join(lines), encoding='utf-8')
    print(f"[fw_gen] EventList.h  → {out_path}  ({len(all_events)} events from {len(modules)} modules)")



def generate_event_registry(modules: list, out_dir: Path) -> None:
    """Emit EventRegistry.h/.c: ID→name/module lookup for diagnostics & logging."""
    all_events = []
    for m in modules:
        for name, val in m['events'].items():
            all_events.append((val, name, m['module']))
    all_events.sort()

    hdr = [
        '/* AUTO-GENERATED by fw_gen.py — do not edit */',
        '#ifndef EVENT_REGISTRY_GEN_H',
        '#define EVENT_REGISTRY_GEN_H',
        '#include <stdint.h>',
        '#include "EventList.h"',
        '',
        'typedef struct {',
        '    EventID_t   id;',
        '    const char *name;',
        '    const char *module;',
        '} EventRegistryEntry_t;',
        '',
        'extern const EventRegistryEntry_t g_event_registry[];',
        'extern const uint16_t             g_event_registry_count;',
        '',
        '/* Lookup helpers */',
        'const char *EventRegistry_Name(EventID_t id);',
        'const char *EventRegistry_Module(EventID_t id);',
        '',
        '#endif /* EVENT_REGISTRY_GEN_H */',
        '',
    ]
    (out_dir / 'EventRegistry.h').write_text('\n'.join(hdr), encoding='utf-8')

    src = [
        '/* AUTO-GENERATED by fw_gen.py — do not edit */',
        '#include "EventRegistry.h"',
        '#include <stddef.h>',
        '',
        'const EventRegistryEntry_t g_event_registry[] = {',
    ]
    for val, name, mod in all_events:
        src.append(f'    {{ 0x{val:04X}U, "{name}", "{mod}" }},')
    src += [
        '};',
        '',
        f'const uint16_t g_event_registry_count = {len(all_events)}U;',
        '',
        'const char *EventRegistry_Name(EventID_t id)',
        '{',
        '    uint16_t i;',
        '    for (i = 0U; i < g_event_registry_count; i++) {',
        '        if (g_event_registry[i].id == id) return g_event_registry[i].name;',
        '    }',
        '    return "UNKNOWN";',
        '}',
        '',
        'const char *EventRegistry_Module(EventID_t id)',
        '{',
        '    uint16_t i;',
        '    for (i = 0U; i < g_event_registry_count; i++) {',
        '        if (g_event_registry[i].id == id) return g_event_registry[i].module;',
        '    }',
        '    return "UNKNOWN";',
        '}',
        '',
    ]
    (out_dir / 'EventRegistry.c').write_text('\n'.join(src), encoding='utf-8')
    print(f"[fw_gen] EventRegistry → {out_dir}/EventRegistry.[ch]  ({len(all_events)} entries)")


def main() -> int:
    parser = argparse.ArgumentParser(description='Firmware code generator')
    parser.add_argument('--event-dir', default='src/event/configs',
                        help='Directory containing EventConfig*.h files')
    parser.add_argument('--out', default='generated',
                        help='Output directory')
    parser.add_argument('--verbose', '-v', action='store_true')
    args = parser.parse_args()

    event_dir = Path(args.event_dir)
    out_dir   = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    # ── Find all EventConfig*.h files ──────────────────────────────────────
    config_files = sorted(event_dir.glob('EventConfig*.h'))
    if not config_files:
        print(f"[fw_gen] WARNING: no EventConfig*.h found in {event_dir}")
        # Write minimal stub so build does not fail
        stub = "/* EventList.h — no event modules found */\n"
        stub += "#ifndef EVENT_LIST_H\n#define EVENT_LIST_H\n"
        stub += "#include <stdint.h>\ntypedef uint16_t EventID_t;\n"
        stub += "#define EVT_INVALID 0x0000U\n#define EVT__COUNT 0U\n"
        stub += "#endif\n"
        (out_dir / 'EventList.h').write_text(stub)
        return 0

    # ── Parse each file ─────────────────────────────────────────────────────
    modules = []
    for f in config_files:
        mod = parse_event_config(f)
        modules.append(mod)
        if args.verbose:
            print(f"  {f.name}: module={mod['module']}, "
                  f"base={hex(mod['base']) if mod['base'] else 'auto'}, "
                  f"events={len(mod['events'])}")

    # ── Validate ─────────────────────────────────────────────────────────────
    errors = validate(modules)
    if errors:
        for e in errors:
            print(f"[fw_gen] ERROR: {e}", file=sys.stderr)
        return 1

    # ── Generate EventList.h ─────────────────────────────────────────────────
    generate_event_list(modules, out_dir / 'EventList.h')

    # ── Generate EventRegistry.h/.c (name lookup table for diagnostics) ─────
    generate_event_registry(modules, out_dir)

    total = sum(len(m['events']) for m in modules)
    print(f"[fw_gen] OK  — {len(modules)} module(s), {total} event(s), 0 collision(s)")
    return 0


if __name__ == '__main__':
    sys.exit(main())
