#!/usr/bin/env python3
"""
rule_engine_gen.py — Rule Engine Configuration Code Generator
==============================================================
Parses the XML configuration and generates:
  - generated/config.h         (limits, sensor/output IDs, pin maps)
  - generated/config.c         (sensor/output lookup helpers)
  - generated/rule_table.h     (extern declarations)
  - generated/rule_table.c     (fully populated static tables)

Usage:
    python3 tools/rule_engine_gen.py --config xml/examples/industrial_automation.xml \
                                     --out generated/

Author: Utkranti Yantra Pvt Ltd
"""

import sys
import os
import xml.etree.ElementTree as ET
import argparse
import re
from datetime import datetime
from collections import defaultdict

# ============================================================
# Helpers
# ============================================================

SENSOR_TYPE_MAP = {
    "TEMPERATURE":   "SENSOR_TYPE_TEMPERATURE",
    "HUMIDITY":      "SENSOR_TYPE_HUMIDITY",
    "CURRENT":       "SENSOR_TYPE_CURRENT",
    "VOLTAGE":       "SENSOR_TYPE_VOLTAGE",
    "FIRE":          "SENSOR_TYPE_FIRE",
    "SMOKE":         "SENSOR_TYPE_SMOKE",
    "GAS":           "SENSOR_TYPE_GAS",
    "ULTRASONIC":    "SENSOR_TYPE_ULTRASONIC",
    "WATER_LEVEL":   "SENSOR_TYPE_WATER_LEVEL",
    "PRESSURE":      "SENSOR_TYPE_PRESSURE",
    "DOOR":          "SENSOR_TYPE_DOOR",
    "PIR_MOTION":    "SENSOR_TYPE_PIR_MOTION",
    "DIGITAL":       "SENSOR_TYPE_DIGITAL",
    "VIRTUAL":       "SENSOR_TYPE_VIRTUAL",
    "RTC_TIME":      "SENSOR_TYPE_RTC_TIME",
    "TOU_SCHEDULE":  "SENSOR_TYPE_TOU_SCHEDULE",
}

OUTPUT_TYPE_MAP = {
    "RELAY":          "OUTPUT_TYPE_RELAY",
    "LED":            "OUTPUT_TYPE_LED",
    "ALARM":          "OUTPUT_TYPE_ALARM",
    "FIRE_ALARM":     "OUTPUT_TYPE_FIRE_ALARM",
    "BUZZER":         "OUTPUT_TYPE_BUZZER",
    "HOOTER":         "OUTPUT_TYPE_HOOTER",
    "PUMP":           "OUTPUT_TYPE_PUMP",
    "FAN":            "OUTPUT_TYPE_FAN",
    "SIREN":          "OUTPUT_TYPE_SIREN",
    "SOLENOID_VALVE": "OUTPUT_TYPE_SOLENOID_VALVE",
    "CONTACTOR":      "OUTPUT_TYPE_CONTACTOR",
}

OP_MAP = {
    "EQ":          "OP_EQ",
    "NE":          "OP_NE",
    "GT":          "OP_GT",
    "GTE":         "OP_GTE",
    "LT":          "OP_LT",
    "LTE":         "OP_LTE",
    "BETWEEN":     "OP_BETWEEN",
    "NOT_BETWEEN": "OP_NOT_BETWEEN",
    "ON":          "OP_ON",
    "OFF":         "OP_OFF",
}

LOGIC_MAP = {
    "AND": "LOGIC_AND",
    "OR":  "LOGIC_OR",
    "NOT": "LOGIC_NOT",
    "XOR": "LOGIC_XOR",
}

ACTION_MAP = {
    "ON":     "ACTION_ON",
    "OFF":    "ACTION_OFF",
    "TOGGLE": "ACTION_TOGGLE",
    "PULSE":  "ACTION_PULSE",
}

SCHED_TYPE_MAP = {
    "DAILY":    "SCHED_DAILY",
    "WEEKLY":   "SCHED_WEEKLY",
    "WEEKEND":  "SCHED_WEEKEND",
    "HOLIDAY":  "SCHED_HOLIDAY",
    "SEASONAL": "SCHED_SEASONAL",
}

IFACE_MAP = {
    "ADC":     "RE_SENSOR_IF_ADC",
    "GPIO":    "RE_SENSOR_IF_GPIO",
    "I2C":     "RE_SENSOR_IF_I2C",
    "SPI":     "RE_SENSOR_IF_SPI",
    "VIRTUAL": "RE_SENSOR_IF_VIRTUAL",
}


def float_to_scaled(v: str) -> int:
    """Convert a decimal string to integer scaled by 100."""
    try:
        return int(round(float(v) * 100))
    except (ValueError, TypeError):
        return 0


def c_str(s: str) -> str:
    """Escape a string for C literal."""
    return s.replace('"', '\\"').replace('\\', '\\\\')


def time_to_hm(t: str):
    """Parse 'HH:MM' → (hour, minute)."""
    parts = t.split(":")
    return int(parts[0]), int(parts[1])


def weekday_mask(s: str) -> int:
    """Convert '0111110' bit string to integer (bit0=Sun)."""
    val = 0
    for i, ch in enumerate(s):
        if ch == '1':
            val |= (1 << i)
    return val


def banner(label: str) -> str:
    line = "=" * 68
    return f"/* {line}\n * {label}\n * {line} */\n"


HEADER_COMMENT = """\
/**
 * AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
 * Generated by: rule_engine_gen.py
 * Timestamp    : {ts}
 * Source XML   : {src}
 *
 * This file is regenerated every time the XML configuration changes.
 * Modify the XML file, then re-run the generator.
 */
"""

# ============================================================
# Validator
# ============================================================

class Validator:
    def __init__(self):
        self.errors = []
        self.warnings = []

    def error(self, msg):
        self.errors.append(f"[ERROR] {msg}")

    def warn(self, msg):
        self.warnings.append(f"[WARN]  {msg}")

    def ok(self) -> bool:
        return len(self.errors) == 0

    def report(self):
        for w in self.warnings:
            print(w, file=sys.stderr)
        for e in self.errors:
            print(e, file=sys.stderr)


def validate(root, v: Validator):
    sensor_ids = set()
    output_ids = set()
    schedule_ids = set()
    rule_ids = set()

    # --- Sensors ---
    for s in root.findall("Sensors/Sensor"):
        sid = int(s.get("id"))
        if sid in sensor_ids:
            v.error(f"Duplicate Sensor id={sid}")
        sensor_ids.add(sid)
        if not (1 <= sid <= 99):
            v.error(f"Sensor id={sid} out of range 1–99")

        mn = float(s.get("min", "-999"))
        mx = float(s.get("max", "9999"))
        if mn >= mx:
            v.error(f"Sensor id={sid}: min({mn}) >= max({mx})")

        t = s.get("type")
        if t not in SENSOR_TYPE_MAP:
            v.error(f"Sensor id={sid}: unknown type '{t}'")

        iface = s.get("interface", "ADC")
        if iface not in IFACE_MAP:
            v.error(f"Sensor id={sid}: unknown interface '{iface}'")

    # --- Outputs ---
    for o in root.findall("Outputs/Output"):
        oid = int(o.get("id"))
        if oid in output_ids:
            v.error(f"Duplicate Output id={oid}")
        output_ids.add(oid)
        if not (1 <= oid <= 99):
            v.error(f"Output id={oid} out of range 1–99")

    # --- Schedules ---
    for sc in root.findall("Schedules/Schedule"):
        scid = int(sc.get("id"))
        if scid in schedule_ids:
            v.error(f"Duplicate Schedule id={scid}")
        schedule_ids.add(scid)
        slots = sc.findall("Slot")
        if len(slots) > 8:
            v.error(f"Schedule id={scid}: more than 8 slots ({len(slots)})")

    # --- Rules ---
    for r in root.findall("Rules/Rule"):
        rid = int(r.get("id"))
        if rid in rule_ids:
            v.error(f"Duplicate Rule id={rid}")
        rule_ids.add(rid)

        conds = r.findall("Conditions/Condition")
        if len(conds) == 0:
            v.error(f"Rule id={rid}: no conditions defined")
        if len(conds) > 8:
            v.error(f"Rule id={rid}: too many conditions ({len(conds)}, max 8)")

        acts = r.findall("Actions/Action")
        if len(acts) == 0:
            v.error(f"Rule id={rid}: no actions defined")
        if len(acts) > 8:
            v.error(f"Rule id={rid}: too many actions ({len(acts)}, max 8)")

        # Check sensor/output refs exist
        for c in conds:
            csid = int(c.get("sensor_id"))
            if csid not in sensor_ids:
                v.error(f"Rule id={rid}: Condition references undefined Sensor id={csid}")
            op = c.get("op")
            if op not in OP_MAP:
                v.error(f"Rule id={rid}: unknown operator '{op}'")
            if op in ("BETWEEN", "NOT_BETWEEN"):
                if c.get("value_lo") is None or c.get("value_hi") is None:
                    v.error(f"Rule id={rid}: BETWEEN/NOT_BETWEEN requires value_lo and value_hi")

        for a in acts:
            aoid = int(a.get("output_id"))
            if aoid not in output_ids:
                v.error(f"Rule id={rid}: Action references undefined Output id={aoid}")

        sched_id = int(r.get("schedule_id", "0"))
        if sched_id != 0 and sched_id not in schedule_ids:
            v.error(f"Rule id={rid}: schedule_id={sched_id} not defined")

        logic = r.get("logic", "AND")
        if logic not in LOGIC_MAP:
            v.error(f"Rule id={rid}: unknown logic '{logic}'")

        prio = int(r.get("priority", "50"))
        if not (0 <= prio <= 255):
            v.error(f"Rule id={rid}: priority {prio} out of range 0–255")


# ============================================================
# Generators
# ============================================================

def gen_config_h(root, src_file: str) -> str:
    sensors   = root.findall("Sensors/Sensor")
    outputs   = root.findall("Outputs/Output")
    rules     = root.findall("Rules/Rule")
    schedules = root.findall("Schedules/Schedule") or []

    ts  = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    out = []
    out.append(HEADER_COMMENT.format(ts=ts, src=src_file))
    out.append("#ifndef CONFIG_H\n#define CONFIG_H\n")
    out.append('#include "re_types.h"\n')
    out.append(banner("Count constants"))
    out.append(f"#define RE_NUM_SENSORS    ({len(sensors)}U)\n")
    out.append(f"#define RE_NUM_OUTPUTS    ({len(outputs)}U)\n")
    out.append(f"#define RE_NUM_RULES      ({len(rules)}U)\n")
    out.append(f"#define RE_NUM_SCHEDULES  ({len(schedules)}U)\n\n")

    out.append(banner("Sensor ID macros"))
    for s in sensors:
        name = re.sub(r'\W+', '_', s.get("name")).upper()
        out.append(f"#define SENSOR_ID_{name:<30s} ({s.get('id')}U)\n")

    out.append("\n")
    out.append(banner("Output ID macros"))
    for o in outputs:
        name = re.sub(r'\W+', '_', o.get("name")).upper()
        out.append(f"#define OUTPUT_ID_{name:<30s} ({o.get('id')}U)\n")

    out.append("\n")
    out.append(banner("Sensor interface type enum (used by HAL dispatch)"))
    out.append(
        "typedef enum {\n"
        "    RE_SENSOR_IF_ADC     = 0,\n"
        "    RE_SENSOR_IF_GPIO    = 1,\n"
        "    RE_SENSOR_IF_I2C     = 2,\n"
        "    RE_SENSOR_IF_SPI     = 3,\n"
        "    RE_SENSOR_IF_VIRTUAL = 4\n"
        "} RE_SensorInterface_t;\n\n"
    )

    out.append(banner("HAL lookup function prototypes (implemented in config.c)"))
    out.append("RE_SensorInterface_t RE_SensorGetInterface(uint8_t sensor_id);\n")
    out.append("int                  RE_SensorGetADCChannel(uint8_t sensor_id);\n")
    out.append("int                  RE_SensorGetGPIOPin(uint8_t sensor_id);\n")
    out.append("uint32_t             RE_SensorGetScale(uint8_t sensor_id);\n")
    out.append("void*                RE_SensorGetGPIOPort(uint8_t sensor_id);\n")
    out.append("int                  RE_OutputGetGPIOPin(uint8_t output_id);\n")
    out.append("void*                RE_OutputGetGPIOPort(uint8_t output_id);\n\n")

    out.append("#endif /* CONFIG_H */\n")
    return "".join(out)


def gen_config_c(root, src_file: str) -> str:
    sensors = root.findall("Sensors/Sensor")
    outputs = root.findall("Outputs/Output")
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    out = []
    out.append(HEADER_COMMENT.format(ts=ts, src=src_file))
    out.append('#include "config.h"\n#include "re_types.h"\n\n')

    # Sensor hardware config lookup tables
    out.append(banner("Sensor hardware configuration lookup tables"))
    out.append("typedef struct {\n"
               "    uint8_t              id;\n"
               "    RE_SensorInterface_t iface;\n"
               "    int                  adc_channel;\n"
               "    int                  gpio_pin;\n"
               "    uint32_t             scale;\n"
               "} SensorHWConfig_t;\n\n")

    out.append(f"static const SensorHWConfig_t s_sensor_hw[{len(sensors)}U] = {{\n")
    for s in sensors:
        iface = IFACE_MAP.get(s.get("interface", "ADC"), "RE_SENSOR_IF_ADC")
        adc   = s.get("adc_channel", "-1")
        gpio  = s.get("gpio_pin", "-1")
        scale = s.get("scale_factor", "100")
        out.append(f"    {{ {int(s.get('id')):>3}U, {iface:<22}, {int(adc):>3}, "
                   f"{int(gpio):>3}, {int(scale)}UL }},  /* {s.get('name')} */\n")
    out.append("};\n\n")

    # Output hardware config
    out.append(banner("Output hardware configuration lookup tables"))
    out.append("typedef struct {\n"
               "    uint8_t id;\n"
               "    int     gpio_pin;\n"
               "} OutputHWConfig_t;\n\n")
    out.append(f"static const OutputHWConfig_t s_output_hw[{len(outputs)}U] = {{\n")
    for o in outputs:
        gpio = o.get("gpio_pin", "-1")
        out.append(f"    {{ {int(o.get('id')):>3}U, {int(gpio):>3} }},  /* {o.get('name')} */\n")
    out.append("};\n\n")

    # Helper function implementations
    out.append(banner("HAL lookup function implementations"))
    out.append(
        "RE_SensorInterface_t RE_SensorGetInterface(uint8_t sensor_id)\n{\n"
        f"    uint16_t i;\n"
        f"    for (i = 0U; i < {len(sensors)}U; i++) {{\n"
        "        if (s_sensor_hw[i].id == sensor_id) { return s_sensor_hw[i].iface; }\n"
        "    }\n"
        "    return RE_SENSOR_IF_ADC;\n}\n\n"
    )
    out.append(
        "int RE_SensorGetADCChannel(uint8_t sensor_id)\n{\n"
        f"    uint16_t i;\n"
        f"    for (i = 0U; i < {len(sensors)}U; i++) {{\n"
        "        if (s_sensor_hw[i].id == sensor_id) { return s_sensor_hw[i].adc_channel; }\n"
        "    }\n"
        "    return -1;\n}\n\n"
    )
    out.append(
        "int RE_SensorGetGPIOPin(uint8_t sensor_id)\n{\n"
        f"    uint16_t i;\n"
        f"    for (i = 0U; i < {len(sensors)}U; i++) {{\n"
        "        if (s_sensor_hw[i].id == sensor_id) { return s_sensor_hw[i].gpio_pin; }\n"
        "    }\n"
        "    return -1;\n}\n\n"
    )
    out.append(
        "uint32_t RE_SensorGetScale(uint8_t sensor_id)\n{\n"
        f"    uint16_t i;\n"
        f"    for (i = 0U; i < {len(sensors)}U; i++) {{\n"
        "        if (s_sensor_hw[i].id == sensor_id) { return s_sensor_hw[i].scale; }\n"
        "    }\n"
        "    return 100UL;\n}\n\n"
    )
    out.append(
        "void* RE_SensorGetGPIOPort(uint8_t sensor_id)\n{\n"
        "    (void)sensor_id;\n"
        "    /* Extend for STM32 port objects (GPIOA, GPIOB, ...) */\n"
        "    return (void*)0;\n}\n\n"
    )
    out.append(
        "int RE_OutputGetGPIOPin(uint8_t output_id)\n{\n"
        f"    uint16_t i;\n"
        f"    for (i = 0U; i < {len(outputs)}U; i++) {{\n"
        "        if (s_output_hw[i].id == output_id) { return s_output_hw[i].gpio_pin; }\n"
        "    }\n"
        "    return -1;\n}\n\n"
    )
    out.append(
        "void* RE_OutputGetGPIOPort(uint8_t output_id)\n{\n"
        "    (void)output_id;\n"
        "    return (void*)0;\n}\n"
    )
    return "".join(out)


def gen_rule_table_h(root, src_file: str) -> str:
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    out = []
    out.append(HEADER_COMMENT.format(ts=ts, src=src_file))
    out.append("#ifndef RULE_TABLE_H\n#define RULE_TABLE_H\n\n")
    out.append('#include "re_engine.h"\n\n')
    out.append(banner("Extern table declarations"))
    out.append("extern const SensorDescriptor_t   g_sensor_table[];\n")
    out.append("extern const OutputDescriptor_t   g_output_table[];\n")
    out.append("extern const RuleDescriptor_t     g_rule_table[];\n")
    out.append("extern const ScheduleDescriptor_t g_schedule_table[];\n\n")
    out.append("extern const uint16_t RE_NUM_SENSORS;\n")
    out.append("extern const uint16_t RE_NUM_OUTPUTS;\n")
    out.append("extern const uint16_t RE_NUM_RULES;\n")
    out.append("extern const uint16_t RE_NUM_SCHEDULES;\n\n")
    out.append("#endif /* RULE_TABLE_H */\n")
    return "".join(out)


def gen_rule_table_c(root, src_file: str) -> str:
    sensors   = root.findall("Sensors/Sensor")
    outputs   = root.findall("Outputs/Output")
    rules     = root.findall("Rules/Rule")
    schedules = root.findall("Schedules/Schedule") or []
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    out = []
    out.append(HEADER_COMMENT.format(ts=ts, src=src_file))
    out.append('#include "rule_table.h"\n')
    out.append('#include "re_engine.h"\n\n')

    # ---- Sensor table ----
    out.append(banner("Sensor descriptor table"))
    out.append(f"const SensorDescriptor_t g_sensor_table[{len(sensors)}U] = {{\n")
    for s in sensors:
        name     = c_str(s.get("name"))
        unit     = c_str(s.get("unit", ""))
        stype    = SENSOR_TYPE_MAP.get(s.get("type"), "SENSOR_TYPE_DIGITAL")
        mn       = float_to_scaled(s.get("min", "-99900"))
        mx       = float_to_scaled(s.get("max", "999900"))
        thi      = float_to_scaled(s.get("threshold_hi", s.get("max", "999900")))
        tlo      = float_to_scaled(s.get("threshold_lo", s.get("min", "-99900")))
        hyst     = float_to_scaled(s.get("hysteresis", "0"))
        interval = int(s.get("sample_interval_ms", "1000"))
        enabled  = "true" if s.get("enabled", "true").lower() == "true" else "false"

        out.append(
            f"    /* Sensor {s.get('id')} — {name} */\n"
            f"    {{\n"
            f"        .id                 = {s.get('id')}U,\n"
            f"        .name               = \"{name}\",\n"
            f"        .type               = {stype},\n"
            f"        .unit               = \"{unit}\",\n"
            f"        .min_value          = {mn}L,\n"
            f"        .max_value          = {mx}L,\n"
            f"        .threshold_hi       = {thi}L,\n"
            f"        .threshold_lo       = {tlo}L,\n"
            f"        .hysteresis         = {hyst}L,\n"
            f"        .sample_interval_ms = {interval}U,\n"
            f"        .enabled            = {enabled}\n"
            f"    }},\n"
        )
    out.append("};\n\n")

    # ---- Output table ----
    out.append(banner("Output descriptor table"))
    out.append(f"const OutputDescriptor_t g_output_table[{len(outputs)}U] = {{\n")
    for o in outputs:
        name     = c_str(o.get("name"))
        otype    = OUTPUT_TYPE_MAP.get(o.get("type"), "OUTPUT_TYPE_RELAY")
        prio     = int(o.get("priority", "50"))
        defst    = "1U" if o.get("default_state", "OFF").upper() == "ON" else "0U"
        fsst     = "1U" if o.get("failsafe_state", "OFF").upper() == "ON" else "0U"

        out.append(
            f"    /* Output {o.get('id')} — {name} */\n"
            f"    {{\n"
            f"        .id            = {o.get('id')}U,\n"
            f"        .name          = \"{name}\",\n"
            f"        .type          = {otype},\n"
            f"        .priority      = {prio}U,\n"
            f"        .default_state = {defst},\n"
            f"        .failsafe_state = {fsst}\n"
            f"    }},\n"
        )
    out.append("};\n\n")

    # ---- Schedule table ----
    out.append(banner("Schedule descriptor table (TOU)"))
    out.append(f"const ScheduleDescriptor_t g_schedule_table[{max(len(schedules), 1)}U] = {{\n")
    if not schedules:
        out.append("    { 0 }  /* No schedules defined */\n")
    for sc in schedules:
        name    = c_str(sc.get("name"))
        sctype  = SCHED_TYPE_MAP.get(sc.get("type", "DAILY"), "SCHED_DAILY")
        enabled = "true" if sc.get("enabled", "true").lower() == "true" else "false"
        slots   = sc.findall("Slot")

        out.append(
            f"    /* Schedule {sc.get('id')} — {name} */\n"
            f"    {{\n"
            f"        .id        = {sc.get('id')}U,\n"
            f"        .name      = \"{name}\",\n"
            f"        .type      = {sctype},\n"
            f"        .num_slots = {len(slots)}U,\n"
            f"        .slots     = {{\n"
        )
        for slot in slots:
            sh, sm = time_to_hm(slot.get("start"))
            eh, em = time_to_hm(slot.get("end"))
            mask   = weekday_mask(slot.get("weekday_mask", "1111111"))
            out.append(
                f"            {{ .start_hour={sh}U, .start_min={sm}U, "
                f".end_hour={eh}U, .end_min={em}U, .weekday_mask=0x{mask:02X}U }},\n"
            )
        out.append(
            f"        }},\n"
            f"        .enabled = {enabled}\n"
            f"    }},\n"
        )
    out.append("};\n\n")

    # ---- Rule table ----
    out.append(banner("Rule descriptor table"))
    out.append(f"const RuleDescriptor_t g_rule_table[{len(rules)}U] = {{\n")
    for r in rules:
        name      = c_str(r.get("name"))
        enabled   = "true" if r.get("enabled", "true").lower() == "true" else "false"
        logic     = LOGIC_MAP.get(r.get("logic", "AND"), "LOGIC_AND")
        on_delay  = int(r.get("on_delay_ms", "0"))
        off_delay = int(r.get("off_delay_ms", "0"))
        sched_id  = int(r.get("schedule_id", "0"))
        prio      = int(r.get("priority", "50"))

        conds = r.findall("Conditions/Condition")
        acts  = r.findall("Actions/Action")

        out.append(
            f"    /* Rule {r.get('id')} — {name} */\n"
            f"    {{\n"
            f"        .id               = {r.get('id')}U,\n"
            f"        .name             = \"{name}\",\n"
            f"        .enabled          = {enabled},\n"
            f"        .num_conditions   = {len(conds)}U,\n"
            f"        .conditions       = {{\n"
        )

        for ci, c in enumerate(conds):
            op = OP_MAP.get(c.get("op"), "OP_EQ")
            if c.get("op") in ("BETWEEN", "NOT_BETWEEN"):
                va = float_to_scaled(c.get("value_lo", "0"))
                vb = float_to_scaled(c.get("value_hi", "0"))
            elif c.get("op") in ("ON", "OFF"):
                va, vb = 0, 0
            else:
                va = float_to_scaled(c.get("value", "0"))
                vb = 0

            out.append(
                f"            [{ci}] = {{ .sensor_id={c.get('sensor_id')}U, "
                f".op={op}, .value_a={va}L, .value_b={vb}L }},\n"
            )

        out.append(
            f"        }},\n"
            f"        .condition_logic  = {logic},\n"
            f"        .on_delay_ms      = {on_delay}U,\n"
            f"        .off_delay_ms     = {off_delay}U,\n"
            f"        .schedule_id      = {sched_id}U,\n"
            f"        .num_actions      = {len(acts)}U,\n"
            f"        .actions          = {{\n"
        )

        for ai, a in enumerate(acts):
            act_type    = ACTION_MAP.get(a.get("state", "ON"), "ACTION_ON")
            duration_ms = int(a.get("duration_ms", "0"))
            out.append(
                f"            [{ai}] = {{ .output_id={a.get('output_id')}U, "
                f".action={act_type}, .duration_ms={duration_ms}U }},\n"
            )

        out.append(
            f"        }},\n"
            f"        .priority         = {prio}U\n"
            f"    }},\n"
        )

    out.append("};\n\n")

    # Count constants
    out.append(banner("Count constants (const so usable in expressions)"))
    out.append(f"const uint16_t RE_NUM_SENSORS   = {len(sensors)}U;\n")
    out.append(f"const uint16_t RE_NUM_OUTPUTS   = {len(outputs)}U;\n")
    out.append(f"const uint16_t RE_NUM_RULES     = {len(rules)}U;\n")
    out.append(f"const uint16_t RE_NUM_SCHEDULES = {max(len(schedules), 1)}U;\n")

    return "".join(out)


# ============================================================
# Main
# ============================================================

def main():
    parser = argparse.ArgumentParser(description="Rule Engine C Code Generator")
    parser.add_argument("--config", required=True, help="Path to XML config file")
    parser.add_argument("--out",    default="generated", help="Output directory")
    parser.add_argument("--no-validate", action="store_true",
                        help="Skip XML validation")
    args = parser.parse_args()

    if not os.path.isfile(args.config):
        print(f"[ERROR] Config file not found: {args.config}", file=sys.stderr)
        sys.exit(1)

    tree = ET.parse(args.config)
    root = tree.getroot()

    # Validation
    if not args.no_validate:
        v = Validator()
        validate(root, v)
        v.report()
        if not v.ok():
            print(f"\n[FAIL] {len(v.errors)} validation error(s). Aborting.", file=sys.stderr)
            sys.exit(2)
        else:
            print(f"[OK] Validation passed ({len(v.warnings)} warning(s))")

    os.makedirs(args.out, exist_ok=True)

    files = {
        "config.h":       gen_config_h(root, args.config),
        "config.c":       gen_config_c(root, args.config),
        "rule_table.h":   gen_rule_table_h(root, args.config),
        "rule_table.c":   gen_rule_table_c(root, args.config),
    }

    for fname, content in files.items():
        path = os.path.join(args.out, fname)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"[GEN] {path}  ({len(content):,} bytes)")

    print(f"\n[DONE] Generated {len(files)} files in '{args.out}/'")


if __name__ == "__main__":
    main()
